// ============================================================================
// LENDER DATABASE — v7.1 Corrected (June 2026)
// ============================================================================
// All lender profiles updated to v7.1 spec with:
//   - Three source tiers: VERIFIED / REPORTED / UNVERIFIED
//   - Confidence scores (60-80 by lender)
//   - Last-verified dates
//   - STR LTV caps (75% for Angel Oak, Visio, others)
//   - Gift funds acceptance (Deephaven accepts)
//   - Corrected FICO/DSCR/LTV data per primary source verification
//   - Easy Street Capital added (100% AirDNA, no haircut)
//   - NexBank/Ready Capital/CoreVest downgraded to <40 confidence
// ============================================================================

export type LenderCategory = 'bank' | 'non_bank' | 'aggregator' | 'institutional';
export type SourceTier = 'VERIFIED' | 'REPORTED' | 'UNVERIFIED';

export interface LenderProfile {
  id: string;
  name: string;
  category: LenderCategory;
  sourceTier: SourceTier;
  confidence: number;
  lastVerified: string;
  maxLtv: number;
  minFico: number | null;
  minDscr: number;
  maxLoanAmount: number;
  minLoanAmount: number;
  baseRateAdjustment: number;
  strPremium: number;
  cashOutPremium: number;
  ioAllowed: boolean;
  ioPenalty: number;
  reserveMonths: number;
  reserveMin: number;
  reserveMax: number;
  strAllowed: boolean;
  strHaircutPct: number;
  strHistoryRequired: number;
  strNotes: string;
  prepayType: 'none' | 'soft_5yr' | 'soft_1yr' | 'step_321' | 'step_3yr' | 'ym' | 'varies';
  prepayNotes: string;
  programs: string[];
  avgCloseDays: number;
  specialties: string[];
  stateRestrictions: string[];
  propertyTypeRestrictions: string[];
  strLtvCap?: number;
  acceptsGiftFunds?: boolean;
  notes: string;
}

// ---------------------------------------------------------------------------
// v7.1 VERIFIED LENDERS (Confidence 70-80)
// ---------------------------------------------------------------------------

export const LENDERS_V71: LenderProfile[] = [
  {
    id: 'griffin_funding',
    name: 'Griffin Funding',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 80,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 620, // v7.1: corrected from 640 [VERIFIED — primary]
    minDscr: 0.75, // v7.1: accepts sub-0.75 [VERIFIED by production data]
    maxLoanAmount: 5000000,
    minLoanAmount: 100000,
    baseRateAdjustment: -12.5,
    strPremium: 37.5,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: AirDNA comps REQUIRED for STR purchase qualification [VERIFIED — primary; prior "No AirDNA" was WRONG]. Cash-out refi requires documented 12-month rental history.',
    prepayType: 'soft_5yr',
    prepayNotes: '5-4-3-2-1% hard; no-PPP available (rate premium)',
    programs: ['DSCR 30-yr Fixed', 'Jumbo $5M+', 'Micro-Asset <400sqft', 'STR with AirDNA'],
    avgCloseDays: 6, // v7.1: 6-day funding capability [VERIFIED]; 2025 avg 34 days
    specialties: ['STR AirDNA qualification', 'sub-0.75 DSCR', 'fast closes (6 days)', 'micro-unit condos'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    strLtvCap: 75, // v7.1: STR LTV cap
    notes: 'v7.1 [VERIFIED — primary]: 62 loans funded May 2026, $20.79M. Avg DSCR 1.14, FICO 729, loan $292K. 75% LTR / 25% STR split. 46 states + DC. 24-48hr approvals.',
  },
  {
    id: 'kiavi',
    name: 'Kiavi',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 75,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 660, // [REPORTED — secondary]
    minDscr: 1.10, // v7.1: sub-1.0 NOT confirmed — prior claim removed
    maxLoanAmount: 3000000,
    minLoanAmount: 75000,
    baseRateAdjustment: -25,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6, // v7.1: Kiavi's own site says no reserve requirements [VERIFIED — primary]; third-party says 6-9mo [REPORTED — conflicting]
    reserveMax: 9,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: AirDNA UNVERIFIED — no Kiavi primary source confirms AirDNA underwriting. Do NOT base STR strategy on Kiavi AirDNA acceptance.',
    prepayType: 'soft_5yr',
    prepayNotes: 'PPP in first 3 years [VERIFIED]; confirm hard/soft per deal',
    programs: ['DSCR 30-yr Fixed', 'Portfolio (5+ properties)', 'Cash-Out Refi'],
    avgCloseDays: 21, // v7.1: 15-30 days, most within 3 weeks [REPORTED]; prior "7-14 day" was optimistic
    specialties: ['Clean SFR purchase', 'portfolio expansion (5+)', 'domestic borrowers'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 [VERIFIED]: US citizen or permanent resident with SSN required. ITIN/foreign national NOT available. 49 states. Portfolio loans for 5+ properties. Rate advertised from ~6% promotional; typical 7.5-11%.',
  },
  {
    id: 'deephaven',
    name: 'Deephaven Mortgage',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 80,
    lastVerified: '2026-06',
    maxLtv: 90, // v7.1: up to 90% advertised, no MI [VERIFIED — primary; prior 80% was WRONG]
    minFico: 660, // v7.1: corrected from 620 [VERIFIED — primary]
    minDscr: 0.75,
    maxLoanAmount: 3500000, // v7.1: $3.5M [VERIFIED; prior "$3M+" corrected]
    minLoanAmount: 100000,
    baseRateAdjustment: 0,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: AirDNA conflicting sources [REPORTED — one secondary says yes; not confirmed by primary]. Verify directly before assuming.',
    prepayType: 'ym',
    prepayNotes: '5-4-3-2-1% standard [UNVERIFIED]; no-PPP available [UNVERIFIED]',
    programs: ['DSCR 30-yr Fixed', 'No-Ratio', 'DSCR 2nd Lien', 'IO 5yr', 'ARM 5/6'],
    avgCloseDays: 21,
    specialties: ['sub-1.0 no-ratio', 'first-time investors (70% LTV cap)', 'high-LTV up to 90%', 'gift funds accepted', 'wholesale/correspondent (broker required)'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    acceptsGiftFunds: true, // v7.1 [VERIFIED — primary]: accepts gift funds for down payment, closing costs, AND reserves
    notes: 'v7.1 [VERIFIED — primary]: Max loan $3.5M, up to 90% LTV (no MI). First-time investor: 70% LTV cap. No limit on total financed properties. Wholesale/correspondent channel — broker required, not direct consumer. ITIN reported yes but UNVERIFIED.',
  },
  {
    id: 'angel_oak',
    name: 'Angel Oak Mortgage Solutions',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 78,
    lastVerified: '2026-06',
    maxLtv: 80, // v7.1: 80% at 720 FICO + 1.00 DSCR [VERIFIED; prior 740 corrected]
    minFico: 680, // v7.1: 680-700 for most programs [REPORTED; 620 from prior unconfirmed]
    minDscr: 1.0,
    maxLoanAmount: 3000000, // v7.1: $1.5M-$3M [CONFLICTING SOURCES]
    minLoanAmount: 100000,
    baseRateAdjustment: 0,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: AirDNA reports accepted for STR programs [REPORTED — secondary; prior "No AirDNA" corrected to conflicting/conditional]. STR program: 80% LTV at 720 FICO + 1.00 DSCR [VERIFIED].',
    prepayType: 'step_3yr',
    prepayNotes: '3-year step-down',
    programs: ['DSCR 30-yr Fixed', 'STR Program', 'Non-Warrantable Condo', 'Exception UW', 'DSCR 2nd Lien'],
    avgCloseDays: 30,
    specialties: ['non-warrantable condos', 'investors with 10+ properties', 'Southeast regional (FL/GA/SC/TN)', 'exception files'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    strLtvCap: 75, // v7.1: STR LTV cap at 75% [REPORTED]
    notes: 'v7.1 [VERIFIED]: 80% LTV at 720 FICO + 1.00 DSCR (prior said 740, corrected). No-ratio: 700 FICO, 75% max LTV (prior said 70%, corrected). Targets investors with 10+ financed properties. Rates run +0.25-0.50% above Visio/Kiavi. Slower turn time than fintech.',
  },
  {
    id: 'visio',
    name: 'Visio Lending',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 76,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 680, // v7.1: 680 (one source cites 660) [CONFLICTING — verify]
    minDscr: 0.75, // v7.1: 0.75 floor reported; 1.0 minimum UNVERIFIED
    maxLoanAmount: 5000000, // v7.1: above $5M requires exec approval [REPORTED; prior $2M hard cap was WRONG]
    minLoanAmount: 100000,
    baseRateAdjustment: -12.5,
    strPremium: 30,
    cashOutPremium: 25,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 100, // v7.1: NO VACANCY FACTOR applied — full rental income used [REPORTED]
    strHistoryRequired: 12,
    strNotes: 'v7.1 [REPORTED]: Established AirDNA partnership + remittance history accepted. Strongest STR coverage. NO VACANCY deduction — validates Dual-Track Principle. A-frames, cabins, yurts accepted.',
    prepayType: 'soft_5yr',
    prepayNotes: '5-4-3-2-1% standard; no-prepay +0.625% [REPORTED — confirmed]',
    programs: ['DSCR 30-yr Fixed', 'STR Specialist', 'ARM 5/6', 'ARM 7/6', 'Flex DSCR'],
    avgCloseDays: 18,
    specialties: ['STR investors any market', 'unique property types', 'no vacancy deduction', 'all three STR income methods'],
    stateRestrictions: ['AK', 'HI'], // v7.1: EXCLUDES Alaska and Hawaii [REPORTED]
    propertyTypeRestrictions: [],
    strLtvCap: 75, // v7.1: STR LTV cap at 75% [REPORTED]
    notes: 'v7.1 [REPORTED]: Income calc = LOWER of actual rent OR appraised market rent, NO VACANCY FACTOR. Min loan $100K. >$5M needs exec approval (not $2M hard cap). 48 states — excludes AK and HI.',
  },
  {
    id: 'lima_one',
    name: 'Lima One Capital',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 74,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 660,
    minDscr: 1.0,
    maxLoanAmount: 5000000, // v7.1: up to $5M [REPORTED; prior $2M was WRONG]
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1 [REPORTED — secondary; upgraded from "case-by-case"]: Formal STR program using specialized underwriting backed by AirDNA and other sources. Produces stronger DSCRs and higher LTVs than standard LT rent.',
    prepayType: 'step_321',
    prepayNotes: '3-2-1% shorter standard [REPORTED]',
    programs: ['DSCR 30-yr Fixed', 'STR Program (AirDNA-backed)', 'Fix-to-Rent', 'Blanket Loans', 'Bridge'],
    avgCloseDays: 21, // v7.1: 7-10 days advertised / ~3 weeks realistic [REPORTED]
    specialties: ['experienced investors', 'bridge-to-DSCR', 'blanket long-hold', 'STR with AirDNA'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    strLtvCap: 80, // STR up to 80% purchase, 75% cash-out [REPORTED]
    notes: 'v7.1 [REPORTED]: Max LTV 80% up to $5M (prior $2M corrected). 41 states [VERIFIED]. Formal STR program with AirDNA backing. Blanket program available — CRITICAL EXIT WARNING applies.',
  },
  {
    id: 'easy_street',
    name: 'Easy Street Capital',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 78,
    lastVerified: '2026-06',
    maxLtv: 80, // STR up to 80% purchase, 75% cash-out [REPORTED]
    minFico: null, // not specified in v7.1
    minDscr: 0, // v7.1: No minimum DSCR [REPORTED]
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: -25,
    strPremium: 0, // v7.1: STR rates from 5.75% — already STR-focused
    cashOutPremium: 25,
    ioAllowed: false,
    ioPenalty: 0,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 100, // v7.1: 100% of AirDNA projected revenue — NO HAIRCUT [VERIFIED]
    strHistoryRequired: 0, // no occupancy-% restrictions
    strNotes: 'v7.1 [VERIFIED]: Uses 100% of AirDNA projected revenue with NO haircut. Verified AirDNA pioneer. No occupancy-% restrictions. Vacation towns and rural STR OK. Solves common STR market-restriction problem.',
    prepayType: 'soft_5yr',
    prepayNotes: '5-year soft prepay [REPORTED]',
    programs: ['STR Specialist', 'AirDNA 100% Income', 'Vacation/Rural STR'],
    avgCloseDays: 21,
    specialties: ['STR investors with strong AirDNA projections', 'vacation towns', 'rural/unique markets', 'no DSCR floor'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    strLtvCap: 80,
    notes: 'v7.1 [VERIFIED]: $500M+ funded across 1,500+ DSCR loans in two years. Direct lender. STR rates from 5.75%. No minimum DSCR. No occupancy restrictions. Confirms Section 10.1 World 2 haircut is lender-specific — Easy Street does NOT apply the 20% haircut most lenders use.',
  },
  {
    id: 'defy',
    name: 'Defy Mortgage',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 75,
    lastVerified: '2026-06',
    maxLtv: 85, // v7.1: 85% for 740+ FICO [VERIFIED]
    minFico: 640, // [VERIFIED]
    minDscr: 0.75, // [VERIFIED]
    maxLoanAmount: 2500000,
    minLoanAmount: 75000,
    baseRateAdjustment: 12.5,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 3, // [VERIFIED] 3 months standard
    reserveMin: 3,
    reserveMax: 6,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1 [VERIFIED]: 740+ FICO unlocks 85% LTV on SFR purchases. Sub-1.0 requires 25-35% down.',
    prepayType: 'soft_5yr',
    prepayNotes: '5-year soft prepay [VERIFIED]',
    programs: ['DSCR 30-yr Fixed', '85% LTV for 740+', 'Sub-1.0 DSCR'],
    avgCloseDays: 18,
    specialties: ['lower FICO files', 'high-LTV deals with strong credit (up to 85%)', 'sub-1.0 DSCR'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 [VERIFIED]: Min FICO 640, Min DSCR 0.75, Sub-1.0 req 25-35% down, Reserve min 3mo. 740+ FICO unlocks 85% LTV.',
  },
  {
    id: 'mbanc',
    name: 'MBANC',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 75,
    lastVerified: '2026-06',
    maxLtv: 80, // [VERIFIED] 80% purchase / 75% cash-out
    minFico: 660, // [VERIFIED]
    minDscr: 0.75, // [VERIFIED]
    maxLoanAmount: 3000000, // [VERIFIED]
    minLoanAmount: 150000, // [VERIFIED]
    baseRateAdjustment: 0,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6, // [VERIFIED] 6mo purchase / 3mo refinance
    reserveMin: 3,
    reserveMax: 6,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'Non-warrantable condos accepted [VERIFIED — key differentiator]',
    prepayType: 'soft_5yr',
    prepayNotes: '5-year soft prepay [VERIFIED]',
    programs: ['DSCR 30-yr Fixed', 'Non-Warrantable Condo', 'Sub-1.0 DSCR', 'Cash-Out Refi'],
    avgCloseDays: 25,
    specialties: ['non-warrantable condos', 'sub-1.0 DSCR', 'cash-out refinances'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 [VERIFIED]: $150K-$3M. 80% purchase / 75% cash-out. 6mo purchase / 3mo refinance reserves.',
  },
  {
    id: 'rcn_capital',
    name: 'RCN Capital',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 72,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 660,
    minDscr: 1.0,
    maxLoanAmount: 2500000,
    minLoanAmount: 75000,
    baseRateAdjustment: -50, // v7.1: 5.50% advertised [VERIFIED] — requires highest FICO/amount tier
    strPremium: 30,
    cashOutPremium: 25,
    ioAllowed: false,
    ioPenalty: 0,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'No-PPP: 10/1 ARM product available [VERIFIED]',
    prepayType: 'none',
    prepayNotes: 'No-PPP on 10/1 ARM [VERIFIED]',
    programs: ['DSCR 30-yr Fixed', '10/1 ARM No-PPP'],
    avgCloseDays: 21,
    specialties: ['well-qualified investors wanting ARM with no PPP'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 [VERIFIED]: Base rate 5.50% advertised (requires highest FICO/amount tier). 10/1 ARM with no PPP available.',
  },
  {
    id: 'new_silver',
    name: 'New Silver',
    category: 'non_bank',
    sourceTier: 'VERIFIED',
    confidence: 70,
    lastVerified: '2026-06',
    maxLtv: 75,
    minFico: 640, // v7.1 [VERIFIED]
    minDscr: 0, // v7.1: No minimum DSCR [VERIFIED]
    maxLoanAmount: 1500000,
    minLoanAmount: 75000,
    baseRateAdjustment: 12.5,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: false,
    ioPenalty: 0,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 70,
    strHistoryRequired: 6,
    strNotes: 'v7.1: 20% minimum down payment generally [VERIFIED]. Speed, STR overlay, algorithm reserves UNVERIFIED.',
    prepayType: 'step_3yr',
    prepayNotes: '3-year step-down',
    programs: ['DSCR 30-yr Fixed', 'No-DSCR-Minimum', 'Speed Closes'],
    avgCloseDays: 14,
    specialties: ['speed-sensitive closes', 'no-DSCR-minimum situations'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 [VERIFIED]: Min DSCR none, FICO 640+, 20% down minimum. 24-48hr term sheets reported.',
  },
];

// ---------------------------------------------------------------------------
// v7.1 DOWNGRADED LENDERS (Confidence <40 — DO NOT USE WITHOUT REVERIFICATION)
// ---------------------------------------------------------------------------

export const LENDERS_DOWNGRADED: LenderProfile[] = [
  {
    id: 'nexbank',
    name: 'NexBank',
    category: 'bank',
    sourceTier: 'UNVERIFIED',
    confidence: 35, // v7.1: downgraded from 68 to <40
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 680,
    minDscr: 1.0,
    maxLoanAmount: 5000000,
    minLoanAmount: 200000,
    baseRateAdjustment: -25,
    strPremium: 30,
    cashOutPremium: 25,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: UNVERIFIED — no public primary or secondary sources confirmed.',
    prepayType: 'step_3yr',
    prepayNotes: 'UNVERIFIED',
    programs: ['DSCR 30-yr Fixed (UNVERIFIED)'],
    avgCloseDays: 30,
    specialties: [],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 DOWNGRADED: Confidence <40. DO NOT USE WITHOUT REVERIFICATION. All prior specific claims (reserve mechanics, rate structures, program floors, LTV grids) are UNVERIFIED.',
  },
  {
    id: 'ready_capital',
    name: 'Ready Capital',
    category: 'non_bank',
    sourceTier: 'UNVERIFIED',
    confidence: 35,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 660,
    minDscr: 1.0,
    maxLoanAmount: 75000000,
    minLoanAmount: 500000,
    baseRateAdjustment: 0,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 9,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: UNVERIFIED — retained as structural reference for blanket loan / yield maintenance warnings only.',
    prepayType: 'ym',
    prepayNotes: 'Yield maintenance — UNVERIFIED for specifics',
    programs: ['DSCR Multifamily (UNVERIFIED)', 'Blanket (structural reference only)'],
    avgCloseDays: 45,
    specialties: [],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 DOWNGRADED: Confidence <40. Retained as structural reference for blanket loan / yield maintenance architecture warnings. Do NOT present as actionable match until direct reverification.',
  },
  {
    id: 'corevest',
    name: 'CoreVest',
    category: 'institutional',
    sourceTier: 'UNVERIFIED',
    confidence: 35,
    lastVerified: '2026-06',
    maxLtv: 75,
    minFico: 680,
    minDscr: 1.0,
    maxLoanAmount: 100000000,
    minLoanAmount: 1000000,
    baseRateAdjustment: -12.5,
    strPremium: 30,
    cashOutPremium: 25,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 6,
    reserveMax: 18,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'v7.1: UNVERIFIED — retained as structural reference for blanket loan exit warnings only.',
    prepayType: 'ym',
    prepayNotes: 'YIELD MAINTENANCE — exit trap warning (structural reference only)',
    programs: ['Blanket Portfolio (structural reference)', 'BTR (UNVERIFIED)'],
    avgCloseDays: 45,
    specialties: [],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'v7.1 DOWNGRADED: Confidence <40. Retained as structural reference for blanket loan exit warnings. Yield maintenance on large portfolio can run six figures. Do NOT present as actionable match.',
  },
];

// ---------------------------------------------------------------------------
// 11 NON-BANK LENDERS FROM CHINESE SPEC (lower confidence — REPORTED tier)
// ---------------------------------------------------------------------------

export const LENDERS_NON_BANK: LenderProfile[] = [
  {
    id: 'ziffy',
    name: 'Ziffy Mortgage',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: null,
    minDscr: 1.0,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 25,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: '75% of rent counted toward DSCR — most generous STR income treatment in market [REPORTED]',
    prepayType: 'step_3yr',
    prepayNotes: '3-year step-down',
    programs: ['DSCR 30-yr Fixed', 'STR Specialist'],
    avgCloseDays: 21,
    specialties: ['STR income (75% haircut)', 'generous STR treatment'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'Most generous STR income treatment — 75% of rent counted toward DSCR [REPORTED]',
  },
  {
    id: 'merchants',
    name: 'Merchants Mortgage',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 75,
    minFico: null,
    minDscr: 1.05,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 37.5,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: '12-month STR operating history required [REPORTED]',
    prepayType: 'soft_1yr',
    prepayNotes: '1-year free (no penalty after year 1)',
    programs: ['DSCR 30-yr Fixed'],
    avgCloseDays: 18,
    specialties: ['fast turnaround', '1-year prepay free'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: '1.05 DSCR, prepay penalty free after Year 1 [REPORTED]',
  },
  {
    id: 'foundation',
    name: 'Foundation Mortgage Corp',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: null,
    minDscr: 1.05,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 37.5,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'Licensed STR only; +0.375% rate bump [REPORTED]',
    prepayType: 'step_321',
    prepayNotes: '3-2-1% step-down',
    programs: ['DSCR 30-yr Fixed', 'Licensed STR'],
    avgCloseDays: 25,
    specialties: ['licensed STR only'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'Licensed STR only; +0.375% rate bump; 3-2-1% prepay [REPORTED]',
  },
  {
    id: 'dscrfinder',
    name: 'DSCRFinder (Aggregator)',
    category: 'aggregator',
    sourceTier: 'REPORTED',
    confidence: 50,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: null,
    minDscr: 1.0,
    maxLoanAmount: 3000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'Aggregator — most underlying funders allow STR; varies [REPORTED]',
    prepayType: 'varies',
    prepayNotes: 'Varies by underlying funder',
    programs: ['Aggregator — Multiple Funders'],
    avgCloseDays: 21,
    specialties: ['aggregator', 'multiple funders', '6-month reserve option'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'Aggregator — can shop multiple funders; 6-month reserve option [REPORTED]',
  },
  {
    id: 'archome_edge',
    name: 'Archome Edge',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: null,
    minDscr: 1.0,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 37.5,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 3,
    strNotes: '3-month STR history required [REPORTED]',
    prepayType: 'soft_5yr',
    prepayNotes: '5-year free (soft)',
    programs: ['DSCR 30-yr Fixed'],
    avgCloseDays: 21,
    specialties: ['low 3-month STR history requirement', '5yr free prepay'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: '3-month STR history required; 5-year free prepay [REPORTED]',
  },
  {
    id: 'archome_access',
    name: 'Archome Access',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 70,
    minFico: null,
    minDscr: 1.15,
    maxLoanAmount: 1500000,
    minLoanAmount: 75000,
    baseRateAdjustment: 25,
    strPremium: 0,
    cashOutPremium: 50,
    ioAllowed: false,
    ioPenalty: 0,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: false,
    strHaircutPct: 0,
    strHistoryRequired: 0,
    strNotes: 'STR NOT ALLOWED [REPORTED]',
    prepayType: 'step_3yr',
    prepayNotes: '3-year step-down',
    programs: ['DSCR 30-yr Fixed', 'No STR'],
    avgCloseDays: 25,
    specialties: ['higher DSCR floor', 'no STR'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: '1.15 DSCR floor; STR not allowed; 70% LTV max [REPORTED]',
  },
  {
    id: 'homebridge',
    name: 'HomeBridge (Access Program)',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 70,
    minFico: null,
    minDscr: 1.15,
    maxLoanAmount: 1500000,
    minLoanAmount: 75000,
    baseRateAdjustment: 25,
    strPremium: 0,
    cashOutPremium: 50,
    ioAllowed: false,
    ioPenalty: 0,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: false,
    strHaircutPct: 0,
    strHistoryRequired: 0,
    strNotes: 'STR EXPLICITLY PROHIBITED [REPORTED]',
    prepayType: 'step_321',
    prepayNotes: '3-2-1% step-down',
    programs: ['DSCR Access Program', 'No STR'],
    avgCloseDays: 30,
    specialties: ['access program', 'STR prohibited'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: '1.15 DSCR (highest); STR explicitly prohibited; 70% LTV; 3-2-1% prepay [REPORTED]',
  },
  {
    id: 'lendqm',
    name: 'LendQM',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 50,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: null,
    minDscr: 1.075,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 37.5,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 9,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 6,
    strNotes: 'Partial allowance; self-serve platform with 60s estimate [REPORTED]',
    prepayType: 'varies',
    prepayNotes: 'Varies by product',
    programs: ['DSCR 30-yr Fixed', 'Self-Serve Tool'],
    avgCloseDays: 14,
    specialties: ['self-serve', '60-second estimate', 'no hard pull'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'Self-serve tool platform; 60-second estimate, no hard pull; flexible 6-12mo reserves [REPORTED]',
  },
  {
    id: 'wantong',
    name: 'Wantong (万通)',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 50,
    lastVerified: '2026-06',
    maxLtv: 75,
    minFico: null,
    minDscr: 1.0,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 12.5,
    strPremium: 25,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'Stock asset proof accepted as alternative income; 1% down product [REPORTED]',
    prepayType: 'none',
    prepayNotes: 'Free — no prepay penalty',
    programs: ['DSCR 30-yr Fixed', '1% Down Product', 'Stock Asset Income'],
    avgCloseDays: 21,
    specialties: ['stock asset income', '1% down product', 'no prepay'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'Accepts stock asset income; 1.00 DSCR; no prepay; ≤75% LTV with 1% down option [REPORTED]',
  },
  {
    id: 'midelfart',
    name: 'MidElfart Capital',
    category: 'non_bank',
    sourceTier: 'REPORTED',
    confidence: 50,
    lastVerified: '2026-06',
    maxLtv: 75,
    minFico: null,
    minDscr: 1.05,
    maxLoanAmount: 2000000,
    minLoanAmount: 75000,
    baseRateAdjustment: 0,
    strPremium: 37.5,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 12,
    reserveMin: 12,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'Transparent STR pricing +0.25-0.50% [REPORTED]',
    prepayType: 'none',
    prepayNotes: 'Free — no prepay penalty',
    programs: ['DSCR 30-yr Fixed'],
    avgCloseDays: 25,
    specialties: ['transparent STR pricing', 'no prepay'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: '1.05+ DSCR; transparent STR pricing +0.25-0.50%; no prepay penalty [REPORTED]',
  },
  {
    id: 'rocket_pro',
    name: 'Rocket Pro TPO',
    category: 'bank',
    sourceTier: 'REPORTED',
    confidence: 55,
    lastVerified: '2026-06',
    maxLtv: 80,
    minFico: 680,
    minDscr: 1.0,
    maxLoanAmount: 3000000,
    minLoanAmount: 150000,
    baseRateAdjustment: -25,
    strPremium: 50,
    cashOutPremium: 37.5,
    ioAllowed: true,
    ioPenalty: 25,
    reserveMonths: 6,
    reserveMin: 6,
    reserveMax: 12,
    strAllowed: true,
    strHaircutPct: 75,
    strHistoryRequired: 12,
    strNotes: 'Nov 2025 launch — most important competitive signal of 2026 [REPORTED]',
    prepayType: 'step_3yr',
    prepayNotes: '3-year step-down',
    programs: ['DSCR 30-yr Fixed', 'Rocket Platform'],
    avgCloseDays: 18,
    specialties: ['Nov 2025 launch', 'major competitive entrant', 'Rocket platform'],
    stateRestrictions: [],
    propertyTypeRestrictions: [],
    notes: 'Launched November 2025 — single most important competitive signal of 2026 [REPORTED]',
  },
];

// All lenders combined — verified first, then non-bank, then downgraded last
export const ALL_LENDERS: LenderProfile[] = [
  ...LENDERS_V71,
  ...LENDERS_NON_BANK,
  ...LENDERS_DOWNGRADED,
];

export function getLenderById(id: string): LenderProfile | undefined {
  return ALL_LENDERS.find((l) => l.id === id);
}

// v7.1: Get only lenders above confidence threshold (60 = usable minimum)
export function getVerifiedLenders(minConfidence: number = 60): LenderProfile[] {
  return ALL_LENDERS.filter((l) => l.confidence >= minConfidence);
}
