import React, { useEffect, useRef } from "react";
import { DcShell, dc } from "../design/dc";

// ─── Content data — three path-driven documents ────────────────────────────

interface LegalSection {
  id: string;
  title: string;
  paras: string[];
}

interface LegalDoc {
  eyebrow: string;
  heading: string;
  sub: string;
  updated: string;
  sections: LegalSection[];
  contactLine: string;
}

const DISCLOSURES: LegalDoc = {
  eyebrow: "Legal & Disclosures",
  heading: "Terms, privacy, and the fine print.",
  sub: "Last updated June 24, 2026. Greenstreet's tools produce estimates for business-purpose lending — not financial, legal, or tax advice.",
  updated: "June 24, 2026",
  sections: [
    {
      id: "estimates",
      title: "1. Estimates, not advice",
      paras: [
        "All figures produced by Greenstreet tools — DSCR, payment, IRR, tax, lender match, and state rules — are estimates generated by deterministic models for business-purpose lending scenarios.",
        "They do not constitute financial, legal, tax, or investment advice. Confirm any figure with a licensed professional before relying on it to close a transaction or file a return.",
      ],
    },
    {
      id: "no-llm",
      title: "2. How figures are produced",
      paras: [
        "Greenstreet does not use a large language model in the calculation path. Every numeric output is computed by versioned, provenance-tracked code. AI is used only to generate plain-language explanations of figures it is explicitly given.",
      ],
    },
    {
      id: "state-rules",
      title: "3. State rule data",
      paras: [
        "Prepayment-penalty, usury, and short-term-rental rules are compiled from statutory sources and updated periodically. Law changes; effective dates and thresholds shown reflect our latest review and may not capture the most recent amendments.",
      ],
    },
    {
      id: "privacy",
      title: "4. Privacy",
      paras: [
        "The pricing tools run without an account and do not require personal information. Inputs you type are processed to compute results and are not sold. Aggregate, de-identified usage may inform product improvements.",
      ],
    },
    {
      id: "lenders",
      title: "5. Lender information",
      paras: [
        "Program boxes in the lender database reflect publicly available guidelines and our research. They are indicative, not commitments. Actual terms are set by each lender at underwriting.",
      ],
    },
    {
      id: "liability",
      title: "6. Limitation of liability",
      paras: [
        'Greenstreet is provided "as is." To the maximum extent permitted by law, Greenstreet Finance is not liable for losses arising from reliance on tool outputs. Your use confirms acceptance of these terms.',
      ],
    },
  ],
  contactLine: "Questions about these terms? Contact legal@greenstreetfinance.com.",
};

const PRIVACY_DOC: LegalDoc = {
  eyebrow: "Legal & Disclosures",
  heading: "Privacy Policy.",
  sub: "How Greenstreet Finance collects, uses, and protects your information.",
  updated: "June 22, 2026",
  sections: [
    {
      id: "what-we-collect",
      title: "1. What we collect",
      paras: [
        "When you use our calculators and tools, we may collect the deal parameters you enter (property price, rent, FICO range, LTV, state). If you request a rate estimate or contact us, we collect your name, email, and phone number. We do not pull your credit or store full Social Security numbers through this website.",
      ],
    },
    {
      id: "how-we-use",
      title: "2. How we use it",
      paras: [
        "We use the information to provide rate estimates, match deals to lenders, respond to your inquiries, and improve our tools. Deal parameters entered into calculators are used to compute results and are not sold.",
      ],
    },
    {
      id: "sharing",
      title: "3. Sharing",
      paras: [
        "We share your contact information with lending partners only when you explicitly request to be matched or quoted. We do not sell personal information. Service providers (hosting, analytics) process data on our behalf under confidentiality terms.",
      ],
    },
    {
      id: "cookies",
      title: "4. Cookies",
      paras: [
        "We use cookies for basic site functionality and analytics. You can control cookie preferences through your browser settings. Some features may not function without essential cookies.",
      ],
    },
    {
      id: "your-rights",
      title: "5. Your rights",
      paras: [
        "You may request access to, correction of, or deletion of your personal information by emailing privacy@greenstreetfinance.com. We respond to verified requests within 30 days.",
      ],
    },
    {
      id: "contact",
      title: "6. Contact",
      paras: ["Questions about this policy? Email privacy@greenstreetfinance.com."],
    },
  ],
  contactLine: "Questions about our privacy practices? Email privacy@greenstreetfinance.com.",
};

const TERMS_DOC: LegalDoc = {
  eyebrow: "Legal & Disclosures",
  heading: "Terms of Service.",
  sub: "The terms governing your use of Greenstreet Finance tools and website.",
  updated: "June 22, 2026",
  sections: [
    {
      id: "not-advice",
      title: "1. Not financial or legal advice",
      paras: [
        "Greenstreet Finance provides educational tools and rate estimates for informational purposes only. Calculator outputs, DSCR figures, rate ranges, and program information are estimates, not commitments, rate locks, or credit approvals. Nothing on this site is legal, tax, or financial advice.",
      ],
    },
    {
      id: "estimates-accuracy",
      title: "2. Estimates and accuracy",
      paras: [
        "Rate ranges, lender criteria, and state prepay rules reflect our best information as of the date shown and change frequently. Verify all figures with the lender and qualified counsel before acting. We are not liable for decisions made based on estimates.",
      ],
    },
    {
      id: "program-estimates",
      title: "3. Lending and program estimates",
      paras: [
        "A pre-screen, quote, or program match is not a commitment to lend, a rate lock, or a credit approval. Final terms are set by Greenstreet Finance after full underwriting. Program parameters and rate ranges change frequently — verify before acting.",
      ],
    },
    {
      id: "acceptable-use",
      title: "4. Acceptable use",
      paras: [
        "You agree not to misuse the tools, scrape data, or attempt to reverse-engineer the engine. The program details, state rules, and content are provided for your business use, not redistribution.",
      ],
    },
    {
      id: "liability",
      title: "5. Limitation of liability",
      paras: [
        "To the maximum extent permitted by law, Greenstreet Finance is not liable for any indirect, incidental, or consequential damages arising from use of the site or reliance on its estimates.",
      ],
    },
    {
      id: "contact",
      title: "6. Contact",
      paras: ["Questions about these terms? Email legal@greenstreetfinance.com."],
    },
  ],
  contactLine: "Questions about these terms? Email legal@greenstreetfinance.com.",
};

// ─── Path → document resolver ───────────────────────────────────────────────
// Uses the `path` prop directly (passed from App with the current pathname and
// re-keyed on each navigation), falling back to window.location.pathname for
// direct URL entry. This avoids the stale-pathname bug where popstate fired
// after the component had already read an old pathname.
function resolveDoc(path: string | undefined): LegalDoc {
  const p = path ?? (typeof window !== "undefined" ? window.location.pathname : "");
  if (p.includes("terms-of-service")) return TERMS_DOC;
  if (p.includes("privacy-policy")) return PRIVACY_DOC;
  return DISCLOSURES;
}

// ─── Sticky TOC highlight ────────────────────────────────────────────────────
function useTocHighlight() {
  useEffect(() => {
    const update = () => {
      const links = Array.from(document.querySelectorAll<HTMLAnchorElement>(".lg-toc-link"));
      if (!links.length) return;
      const scrollY = window.scrollY + 120;
      let active = links[0];
      for (const link of links) {
        const id = link.getAttribute("href")?.replace("#", "");
        if (!id) continue;
        const el = document.getElementById(id);
        if (el && el.getBoundingClientRect().top + window.scrollY <= scrollY) {
          active = link;
        }
      }
      links.forEach((l) => {
        const isActive = l === active;
        l.style.color = isActive ? dc.dark : "rgba(0,55,56,0.50)";
        l.style.fontWeight = isActive ? "600" : "500";
        l.style.borderLeftColor = isActive ? dc.rain : "transparent";
      });
    };
    window.addEventListener("scroll", update, { passive: true });
    update();
    return () => window.removeEventListener("scroll", update);
  }, []);
}

// ─── Sub-nav pill buttons (switch between the three docs) ────────────────────
function DocSwitcher({
  current,
}: {
  current: LegalDoc;
}) {
  const pills: { label: string; path: string; view: string }[] = [
    { label: "Disclosures", path: "/legal", view: "legal" },
    { label: "Privacy Policy", path: "/legal/privacy-policy", view: "legal/privacy-policy" },
    { label: "Terms of Service", path: "/legal/terms-of-service", view: "legal/terms-of-service" },
  ];

  const currentHeading = current.heading.replace(".", "");

  return (
    <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 28 }}>
      {pills.map((p) => {
        const isActive =
          (p.label === "Disclosures" && currentHeading === "Terms, privacy, and the fine print") ||
          (p.label === "Privacy Policy" && currentHeading === "Privacy Policy") ||
          (p.label === "Terms of Service" && currentHeading === "Terms of Service");
        return (
          <button
            key={p.label}
            onClick={() => {
              // Navigate via history + popstate so App's router resolves the
              // new path. The three legal docs share the "legal" PageView and
              // are disambiguated by pathname (see resolveDoc), so we cannot
              // round-trip through onNavigate(view) — it has no matching case.
              window.history.pushState({}, "", p.path);
              window.dispatchEvent(new PopStateEvent("popstate"));
              window.scrollTo({ top: 0 });
            }}
            style={{
              padding: "9px 18px",
              borderRadius: 6,
              border: `1px solid ${isActive ? dc.rain : "rgba(0,55,56,0.20)"}`,
              background: isActive ? dc.dark : "transparent",
              color: isActive ? dc.cream : dc.dark,
              fontSize: 13,
              fontWeight: 600,
              letterSpacing: "-0.01em",
              cursor: "pointer",
              fontFamily: dc.sans,
              transition: "background .15s, border-color .15s, color .15s",
            }}
          >
            {p.label}
          </button>
        );
      })}
    </div>
  );
}

// ─── Main page ───────────────────────────────────────────────────────────────
export default function LegalPage({
  onBack,
  onNavigate,
  path,
}: {
  onBack: () => void;
  onNavigate: (v: any) => void;
  path?: string;
}) {
  const doc = resolveDoc(path);
  const toc = doc.sections.map((s) => ({
    label: s.title.replace(/^\d+\.\s*/, ""),
    href: "#" + s.id,
  }));

  useTocHighlight();

  useEffect(() => {
    document.title = `${doc.heading.replace(".", "")} | Greenstreet Finance`;
    window.scrollTo(0, 0);
  }, [path]);

  return (
    <DcShell
      onNavigate={onNavigate}
      navLinks={[
        { label: "DSCR Calc", view: "dscr-calculator" },
        { label: "Lender Intel", view: "lender-intel" },
        { label: "State Rules", view: "state-laws" },
      ]}
      cta={{ label: "Price a deal →", view: "dscr-calculator" }}
    >
      {/* TOC link styles — flat 1px borders, no blur, no glass */}
      <style>{`
        .lg-toc-link {
          transition: color .12s, border-left-color .12s;
          text-decoration: none;
          display: block;
          font-size: 14px;
          font-weight: 500;
          color: rgba(0,55,56,0.50);
          padding: 8px 0 8px 14px;
          letter-spacing: -0.01em;
          border-left: 2px solid transparent;
        }
        .lg-toc-link:hover { color: ${dc.dark} !important; }
        @media (max-width: 760px) { .lg-toc-col { display: none !important; } }
      `}</style>

      {/* ── HERO ── solid pistachio, no blur/glow */}
      <section
        style={{
          background: dc.mintBg,
          padding: "clamp(56px,7vh,96px) clamp(1.5rem,4vw,3rem) clamp(40px,5vh,64px)",
          overflow: "hidden",
        }}
      >
        <div id="gs-hero-content" style={{ maxWidth: 1080, margin: "0 auto" }}>
          <div
            style={{
              fontSize: 13,
              fontWeight: 500,
              color: "rgba(0,55,56,0.55)",
              marginBottom: 20,
              letterSpacing: "-0.01em",
            }}
          >
            {doc.eyebrow}
          </div>
          <h1
            style={{
              fontSize: "clamp(40px,5.5vw,84px)",
              fontWeight: 600,
              lineHeight: 0.99,
              letterSpacing: "-0.035em",
              margin: "0 0 18px",
              maxWidth: "18ch",
              color: dc.dark,
            }}
          >
            {doc.heading}
          </h1>
          <p
            style={{
              fontSize: "clamp(16px,1.4vw,20px)",
              fontWeight: 500,
              lineHeight: 1.5,
              letterSpacing: "-0.02em",
              color: "rgba(0,55,56,0.62)",
              maxWidth: "54ch",
              margin: 0,
            }}
          >
            {doc.sub}
          </p>
          <DocSwitcher current={doc} />
        </div>
      </section>

      {/* ── CONTENT: sticky TOC + sections card ── */}
      <section
        className="gs-reveal"
        style={{
          background: dc.cream,
          padding: "clamp(48px,6vw,80px) clamp(1.5rem,4vw,3rem) clamp(72px,10vh,120px)",
        }}
      >
        <div
          style={{
            maxWidth: 1080,
            margin: "0 auto",
            display: "grid",
            gridTemplateColumns: "220px 1fr",
            gap: 48,
            alignItems: "start",
          }}
        >
          {/* Sticky TOC sidebar */}
          <nav
            className="lg-toc-col"
            aria-label="Section navigation"
            style={{
              position: "sticky",
              top: 96,
              display: "flex",
              flexDirection: "column",
              gap: 0,
            }}
          >
            {toc.map((t) => (
              <a key={t.href} href={t.href} className="lg-toc-link">
                {t.label}
              </a>
            ))}
          </nav>

          {/* Sections card — solid white, flat 1px border */}
          <div
            style={{
              background: dc.white,
              borderRadius: 9,
              border: "1px solid rgba(0,55,56,0.10)",
              padding: "clamp(32px,4vw,56px)",
            }}
          >
            {doc.sections.map((s) => (
              <div
                key={s.id}
                id={s.id}
                style={{ marginBottom: 40, scrollMarginTop: 100 }}
              >
                <h2
                  style={{
                    fontSize: "clamp(22px,2.4vw,30px)",
                    fontWeight: 600,
                    letterSpacing: "-0.03em",
                    margin: "0 0 16px",
                    color: dc.dark,
                  }}
                >
                  {s.title}
                </h2>
                {s.paras.map((para, i) => (
                  <p
                    key={i}
                    style={{
                      fontSize: 16,
                      fontWeight: 500,
                      lineHeight: 1.65,
                      color: "rgba(0,55,56,0.70)",
                      margin: "0 0 14px",
                      letterSpacing: "-0.01em",
                    }}
                  >
                    {para}
                  </p>
                ))}
              </div>
            ))}

            {/* Footer line */}
            <div
              style={{
                borderTop: "1px solid rgba(0,55,56,0.12)",
                paddingTop: 24,
                fontSize: 14,
                fontWeight: 500,
                color: "rgba(0,55,56,0.50)",
                letterSpacing: "-0.01em",
              }}
            >
              {doc.contactLine}
            </div>
          </div>
        </div>
      </section>
    </DcShell>
  );
}
